name: Publish API
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  DATABASE_URL: mysql://{{{mysqlName}}}:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/{{{mysqlName}}}
  IS_PRODUCTION: 1
  ORIGIN: https://{{{projectName}}}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: install
        run: npm install
      - name: build
        run: npx fuego compile
      - name: deploy
        run: npx fuego publish
