name: Publish Data Infrastructure
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "data/**"
      - ".github/workflows/data.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  DATABASE_URL: mysql://{{{mysqlName}}}:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/{{{mysqlName}}}
  IS_PRODUCTION: 1
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: get
        run: npx cdktf get
      - name: plan
        run: npx cdktf plan
      - name: migrate
        run: npx fuego migrate
