name: Publish package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm t
        env:
          NODE_ENV: test
          DEBUG: true
      - name: authenticate
        run: echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
      - name: prepare
        run: cp LICENSE README.md package.json dist
      - name: publish
        run: npm publish --access public
        working-directory: dist
