name: Publish package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package.json"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm t
        env:
          NODE_ENV: test
          DEBUG: true
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          check-version: false
